# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.24

# set version label
ARG BUILD_DATE
ARG VERSION
ARG WIREGUARD_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="ljrh"

RUN \
  if [ -z "${WIREGUARD_RELEASE+x}" ]; then \
  WIREGUARD_RELEASE=$(curl -sL "http://dl-cdn.alpinelinux.org/alpine/v3.24/main/aarch64/APKINDEX.tar.gz" | tar -xz -C /tmp \
    && awk '/^P:wireguard-tools$/,/V:/' /tmp/APKINDEX | sed -n 2p | sed 's/^V://'); \
  fi && \
  echo "**** install dependencies ****" && \
  apk update && \
  apk upgrade && \
  apk add --no-cache \
    bc \
    grep \
    iproute2 \
    iptables \
    ip6tables \
    iputils \
    kmod \
    libcap-utils \
    libqrencode-tools \
    nftables \
    openresolv \
    wireguard-tools==${WIREGUARD_RELEASE} && \
  apk add --no-cache --virtual .build-deps \
    git \
    go \
    make && \
  echo "wireguard" >> /etc/modules && \
  echo "**** build coredns from source ****" && \
  COREDNS_VERSION=1.14.7 && \
  GOLANG_VERSION=1.26.8 && \
  export GOTOOLCHAIN=go${GOLANG_VERSION} && \
  cd /tmp && \
  git clone --depth 1 --branch v${COREDNS_VERSION} https://github.com/coredns/coredns.git && \
  cd coredns && \
  go get google.golang.org/grpc@v1.83.2 \
    go.etcd.io/etcd/client/v3@v3.6.14 \
    go.etcd.io/etcd/client/pkg/v3@v3.6.14 && \
  go mod edit -replace=golang.org/x/crypto=golang.org/x/crypto@v0.56.0 && \
  go mod edit -replace=golang.org/x/mod=golang.org/x/mod@v0.40.0 && \
  go mod tidy && \
  CGO_ENABLED=1 make GOLANG_VERSION=${GOLANG_VERSION} && \
  install -Dm755 coredns /usr/bin/coredns && \
  cd / && \
  rm -rf /tmp/coredns && \
  apk del .build-deps && \
# deliberate: curl, coreutils and jq ship in the base image and carry unfixed
# CVEs. Nothing in this image needs them at runtime, and the base image's
# /docker-mods script reinstalls curl and jq on demand when DOCKER_MODS is set.
  apk del curl coreutils jq && \
  rm -rf /etc/wireguard && \
  ln -s /config/wg_confs /etc/wireguard && \
  printf "Linuxserver.io version: ${VERSION}\nBuild-date: ${BUILD_DATE}" > /build_version && \
  echo "**** clean up ****" && \
  rm -rf \
    /root/go \
    /tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 51820/udp
