# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.23

# set version label
ARG BUILD_DATE
ARG VERSION
ARG WIREGUARD_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thespad"

RUN \
  if [ -z ${WIREGUARD_RELEASE+x} ]; then \
  WIREGUARD_RELEASE=$(curl -sL "http://dl-cdn.alpinelinux.org/alpine/v3.23/main/aarch64/APKINDEX.tar.gz" | tar -xz -C /tmp \
    && awk '/^P:wireguard-tools$/,/V:/' /tmp/APKINDEX | sed -n 2p | sed 's/^V://'); \
  fi && \
  echo "**** install dependencies ****" && \
  apk update && \
  apk upgrade && \
  apk add --no-cache \
    bc \
    grep \
    iproute2 \
    iptables \
    ip6tables \
    kmod \
    libcap-utils \
    libqrencode-tools \
    nftables \
    openresolv \
    wireguard-tools==${WIREGUARD_RELEASE} && \
  apk add --no-cache --virtual .build-deps \
    git \
    go \
    make \
    unbound-dev && \
  echo "wireguard" >> /etc/modules && \
  echo "**** build coredns from source ****" && \
  COREDNS_VERSION=1.14.7 && \
  cd /tmp && \
  git clone --depth 1 --branch v${COREDNS_VERSION} https://github.com/coredns/coredns.git && \
  cd coredns && \
  GOTOOLCHAIN=go1.26.8 go get google.golang.org/grpc@v1.83.2 \
    go.etcd.io/etcd/client/v3@v3.6.14 \
    go.etcd.io/etcd/client/pkg/v3@v3.6.14 && \
  GOTOOLCHAIN=go1.26.8 go mod edit -replace=golang.org/x/crypto=golang.org/x/crypto@v0.56.0 && \
  GOTOOLCHAIN=go1.26.8 go mod edit -replace=golang.org/x/mod=golang.org/x/mod@v0.40.0 && \
  GOTOOLCHAIN=go1.26.8 go mod tidy && \
  CGO_ENABLED=1 make GOLANG_VERSION=1.26.8 && \
  install -Dm755 coredns /usr/bin/coredns && \
  cd / && \
  rm -rf /tmp/coredns && \
  apk del .build-deps && \
  apk del curl coreutils jq && \
  sed -i 's|\[\[ $proto == -4 \]\] && cmd sysctl -q net\.ipv4\.conf\.all\.src_valid_mark=1|[[ $proto == -4 ]] \&\& [[ $(sysctl -n net.ipv4.conf.all.src_valid_mark) != 1 ]] \&\& cmd sysctl -q net.ipv4.conf.all.src_valid_mark=1|' /usr/bin/wg-quick && \
  rm -rf /etc/wireguard && \
  ln -s /config/wg_confs /etc/wireguard && \
  printf "Linuxserver.io version: ${VERSION}\nBuild-date: ${BUILD_DATE}" > /build_version && \
  echo "**** clean up ****" && \
  rm -rf \
    /root/go \
    /tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 51820/udp
